# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 09:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043c\u0435\u0442\u043a\u0430 \u043e \u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': '\u043f\u043e\u0441\u0442 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438',
                'verbose_name_plural': '\u043f\u043e\u0441\u0442\u044b \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('posted', models.DateTimeField(default=datetime.datetime(2018, 1, 22, 14, 35, 0, 28613), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044f \u0431\u043b\u043e\u0433\u0430',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u044c\u0438 \u0431\u043b\u043e\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='\u0411\u043b\u043e\u0433 \u043f\u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446 \u0431\u043b\u043e\u0433\u0430')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430',
                'verbose_name_plural': '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Post', verbose_name='\u041f\u043e\u0441\u0442 \u043b\u0435\u043d\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446 \u0431\u043b\u043e\u0433\u0430'),
        ),
    ]
