# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 14, 35, 21, 683629), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
